# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /__w/OpenSiv3DForWebv0.6Samples/OpenSiv3DForWebv0.6Samples

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /__w/OpenSiv3DForWebv0.6Samples/OpenSiv3DForWebv0.6Samples/Build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /__w/OpenSiv3DForWebv0.6Samples/OpenSiv3DForWebv0.6Samples/Build/CMakeFiles /__w/OpenSiv3DForWebv0.6Samples/OpenSiv3DForWebv0.6Samples/Build/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /__w/OpenSiv3DForWebv0.6Samples/OpenSiv3DForWebv0.6Samples/Build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Siv3DAppData

# Build rule for target.
Siv3DAppData: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Siv3DAppData
.PHONY : Siv3DAppData

# fast build rule for target.
Siv3DAppData/fast:
	$(MAKE) -f CMakeFiles/Siv3DAppData.dir/build.make CMakeFiles/Siv3DAppData.dir/build
.PHONY : Siv3DAppData/fast

#=============================================================================
# Target rules for targets named MainWebGPU

# Build rule for target.
MainWebGPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MainWebGPU
.PHONY : MainWebGPU

# fast build rule for target.
MainWebGPU/fast:
	$(MAKE) -f Main/CMakeFiles/MainWebGPU.dir/build.make Main/CMakeFiles/MainWebGPU.dir/build
.PHONY : MainWebGPU/fast

#=============================================================================
# Target rules for targets named AsyncFileDownloadWebGPU

# Build rule for target.
AsyncFileDownloadWebGPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AsyncFileDownloadWebGPU
.PHONY : AsyncFileDownloadWebGPU

# fast build rule for target.
AsyncFileDownloadWebGPU/fast:
	$(MAKE) -f AsyncFileDownload/CMakeFiles/AsyncFileDownloadWebGPU.dir/build.make AsyncFileDownload/CMakeFiles/AsyncFileDownloadWebGPU.dir/build
.PHONY : AsyncFileDownloadWebGPU/fast

#=============================================================================
# Target rules for targets named DragDropWebGPU

# Build rule for target.
DragDropWebGPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DragDropWebGPU
.PHONY : DragDropWebGPU

# fast build rule for target.
DragDropWebGPU/fast:
	$(MAKE) -f DragDrop/CMakeFiles/DragDropWebGPU.dir/build.make DragDrop/CMakeFiles/DragDropWebGPU.dir/build
.PHONY : DragDropWebGPU/fast

#=============================================================================
# Target rules for targets named MicrophoneWebGPU

# Build rule for target.
MicrophoneWebGPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MicrophoneWebGPU
.PHONY : MicrophoneWebGPU

# fast build rule for target.
MicrophoneWebGPU/fast:
	$(MAKE) -f Microphone/CMakeFiles/MicrophoneWebGPU.dir/build.make Microphone/CMakeFiles/MicrophoneWebGPU.dir/build
.PHONY : MicrophoneWebGPU/fast

#=============================================================================
# Target rules for targets named MaterialIconWebGPU

# Build rule for target.
MaterialIconWebGPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MaterialIconWebGPU
.PHONY : MaterialIconWebGPU

# fast build rule for target.
MaterialIconWebGPU/fast:
	$(MAKE) -f MaterialIcon/CMakeFiles/MaterialIconWebGPU.dir/build.make MaterialIcon/CMakeFiles/MaterialIconWebGPU.dir/build
.PHONY : MaterialIconWebGPU/fast

#=============================================================================
# Target rules for targets named QRReaderWebGPU

# Build rule for target.
QRReaderWebGPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 QRReaderWebGPU
.PHONY : QRReaderWebGPU

# fast build rule for target.
QRReaderWebGPU/fast:
	$(MAKE) -f QRReader/CMakeFiles/QRReaderWebGPU.dir/build.make QRReader/CMakeFiles/QRReaderWebGPU.dir/build
.PHONY : QRReaderWebGPU/fast

#=============================================================================
# Target rules for targets named TerrainWebGPU

# Build rule for target.
TerrainWebGPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TerrainWebGPU
.PHONY : TerrainWebGPU

# fast build rule for target.
TerrainWebGPU/fast:
	$(MAKE) -f Terrain/CMakeFiles/TerrainWebGPU.dir/build.make Terrain/CMakeFiles/TerrainWebGPU.dir/build
.PHONY : TerrainWebGPU/fast

#=============================================================================
# Target rules for targets named VideoReaderWebGPU

# Build rule for target.
VideoReaderWebGPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 VideoReaderWebGPU
.PHONY : VideoReaderWebGPU

# fast build rule for target.
VideoReaderWebGPU/fast:
	$(MAKE) -f VideoReader/CMakeFiles/VideoReaderWebGPU.dir/build.make VideoReader/CMakeFiles/VideoReaderWebGPU.dir/build
.PHONY : VideoReaderWebGPU/fast

#=============================================================================
# Target rules for targets named WebCamWebGPU

# Build rule for target.
WebCamWebGPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 WebCamWebGPU
.PHONY : WebCamWebGPU

# fast build rule for target.
WebCamWebGPU/fast:
	$(MAKE) -f WebCam/CMakeFiles/WebCamWebGPU.dir/build.make WebCam/CMakeFiles/WebCamWebGPU.dir/build
.PHONY : WebCamWebGPU/fast

#=============================================================================
# Target rules for targets named AdditionalEmojiWebGPU

# Build rule for target.
AdditionalEmojiWebGPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AdditionalEmojiWebGPU
.PHONY : AdditionalEmojiWebGPU

# fast build rule for target.
AdditionalEmojiWebGPU/fast:
	$(MAKE) -f AdditionalEmoji/CMakeFiles/AdditionalEmojiWebGPU.dir/build.make AdditionalEmoji/CMakeFiles/AdditionalEmojiWebGPU.dir/build
.PHONY : AdditionalEmojiWebGPU/fast

#=============================================================================
# Target rules for targets named EmpoweredAudioWebGPU

# Build rule for target.
EmpoweredAudioWebGPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 EmpoweredAudioWebGPU
.PHONY : EmpoweredAudioWebGPU

# fast build rule for target.
EmpoweredAudioWebGPU/fast:
	$(MAKE) -f EmpoweredAudio/CMakeFiles/EmpoweredAudioWebGPU.dir/build.make EmpoweredAudio/CMakeFiles/EmpoweredAudioWebGPU.dir/build
.PHONY : EmpoweredAudioWebGPU/fast

#=============================================================================
# Target rules for targets named KDTreeWebGPU

# Build rule for target.
KDTreeWebGPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 KDTreeWebGPU
.PHONY : KDTreeWebGPU

# fast build rule for target.
KDTreeWebGPU/fast:
	$(MAKE) -f KDTree/CMakeFiles/KDTreeWebGPU.dir/build.make KDTree/CMakeFiles/KDTreeWebGPU.dir/build
.PHONY : KDTreeWebGPU/fast

#=============================================================================
# Target rules for targets named GeoJsonWebGPU

# Build rule for target.
GeoJsonWebGPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GeoJsonWebGPU
.PHONY : GeoJsonWebGPU

# fast build rule for target.
GeoJsonWebGPU/fast:
	$(MAKE) -f GeoJson/CMakeFiles/GeoJsonWebGPU.dir/build.make GeoJson/CMakeFiles/GeoJsonWebGPU.dir/build
.PHONY : GeoJsonWebGPU/fast

#=============================================================================
# Target rules for targets named GrabCutWebGPU

# Build rule for target.
GrabCutWebGPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GrabCutWebGPU
.PHONY : GrabCutWebGPU

# fast build rule for target.
GrabCutWebGPU/fast:
	$(MAKE) -f GrabCut/CMakeFiles/GrabCutWebGPU.dir/build.make GrabCut/CMakeFiles/GrabCutWebGPU.dir/build
.PHONY : GrabCutWebGPU/fast

#=============================================================================
# Target rules for targets named Spline2DWebGPU

# Build rule for target.
Spline2DWebGPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Spline2DWebGPU
.PHONY : Spline2DWebGPU

# fast build rule for target.
Spline2DWebGPU/fast:
	$(MAKE) -f Spline2D/CMakeFiles/Spline2DWebGPU.dir/build.make Spline2D/CMakeFiles/Spline2DWebGPU.dir/build
.PHONY : Spline2DWebGPU/fast

#=============================================================================
# Target rules for targets named P2WheelJointWebGPU

# Build rule for target.
P2WheelJointWebGPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 P2WheelJointWebGPU
.PHONY : P2WheelJointWebGPU

# fast build rule for target.
P2WheelJointWebGPU/fast:
	$(MAKE) -f P2WheelJoint/CMakeFiles/P2WheelJointWebGPU.dir/build.make P2WheelJoint/CMakeFiles/P2WheelJointWebGPU.dir/build
.PHONY : P2WheelJointWebGPU/fast

#=============================================================================
# Target rules for targets named PackRectanglesWebGPU

# Build rule for target.
PackRectanglesWebGPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PackRectanglesWebGPU
.PHONY : PackRectanglesWebGPU

# fast build rule for target.
PackRectanglesWebGPU/fast:
	$(MAKE) -f PackRectangles/CMakeFiles/PackRectanglesWebGPU.dir/build.make PackRectangles/CMakeFiles/PackRectanglesWebGPU.dir/build
.PHONY : PackRectanglesWebGPU/fast

#=============================================================================
# Target rules for targets named PolygonOutlineWebGPU

# Build rule for target.
PolygonOutlineWebGPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PolygonOutlineWebGPU
.PHONY : PolygonOutlineWebGPU

# fast build rule for target.
PolygonOutlineWebGPU/fast:
	$(MAKE) -f PolygonOutline/CMakeFiles/PolygonOutlineWebGPU.dir/build.make PolygonOutline/CMakeFiles/PolygonOutlineWebGPU.dir/build
.PHONY : PolygonOutlineWebGPU/fast

#=============================================================================
# Target rules for targets named PerlinNoiseWebGPU

# Build rule for target.
PerlinNoiseWebGPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PerlinNoiseWebGPU
.PHONY : PerlinNoiseWebGPU

# fast build rule for target.
PerlinNoiseWebGPU/fast:
	$(MAKE) -f PerlinNoise/CMakeFiles/PerlinNoiseWebGPU.dir/build.make PerlinNoise/CMakeFiles/PerlinNoiseWebGPU.dir/build
.PHONY : PerlinNoiseWebGPU/fast

#=============================================================================
# Target rules for targets named QRCodeWebGPU

# Build rule for target.
QRCodeWebGPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 QRCodeWebGPU
.PHONY : QRCodeWebGPU

# fast build rule for target.
QRCodeWebGPU/fast:
	$(MAKE) -f QRCode/CMakeFiles/QRCodeWebGPU.dir/build.make QRCode/CMakeFiles/QRCodeWebGPU.dir/build
.PHONY : QRCodeWebGPU/fast

#=============================================================================
# Target rules for targets named RayIntersectionWebGPU

# Build rule for target.
RayIntersectionWebGPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 RayIntersectionWebGPU
.PHONY : RayIntersectionWebGPU

# fast build rule for target.
RayIntersectionWebGPU/fast:
	$(MAKE) -f RayIntersection/CMakeFiles/RayIntersectionWebGPU.dir/build.make RayIntersection/CMakeFiles/RayIntersectionWebGPU.dir/build
.PHONY : RayIntersectionWebGPU/fast

#=============================================================================
# Target rules for targets named NavMeshWebGPU

# Build rule for target.
NavMeshWebGPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NavMeshWebGPU
.PHONY : NavMeshWebGPU

# fast build rule for target.
NavMeshWebGPU/fast:
	$(MAKE) -f NavMesh/CMakeFiles/NavMeshWebGPU.dir/build.make NavMesh/CMakeFiles/NavMeshWebGPU.dir/build
.PHONY : NavMeshWebGPU/fast

#=============================================================================
# Target rules for targets named SoftShapeWebGPU

# Build rule for target.
SoftShapeWebGPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SoftShapeWebGPU
.PHONY : SoftShapeWebGPU

# fast build rule for target.
SoftShapeWebGPU/fast:
	$(MAKE) -f SoftShape/CMakeFiles/SoftShapeWebGPU.dir/build.make SoftShape/CMakeFiles/SoftShapeWebGPU.dir/build
.PHONY : SoftShapeWebGPU/fast

#=============================================================================
# Target rules for targets named ViewFrustumWebGPU

# Build rule for target.
ViewFrustumWebGPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ViewFrustumWebGPU
.PHONY : ViewFrustumWebGPU

# fast build rule for target.
ViewFrustumWebGPU/fast:
	$(MAKE) -f ViewFrustum/CMakeFiles/ViewFrustumWebGPU.dir/build.make ViewFrustum/CMakeFiles/ViewFrustumWebGPU.dir/build
.PHONY : ViewFrustumWebGPU/fast

#=============================================================================
# Target rules for targets named TCPonWebSocketWebGPU

# Build rule for target.
TCPonWebSocketWebGPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TCPonWebSocketWebGPU
.PHONY : TCPonWebSocketWebGPU

# fast build rule for target.
TCPonWebSocketWebGPU/fast:
	$(MAKE) -f TCPonWebSocket/CMakeFiles/TCPonWebSocketWebGPU.dir/build.make TCPonWebSocket/CMakeFiles/TCPonWebSocketWebGPU.dir/build
.PHONY : TCPonWebSocketWebGPU/fast

#=============================================================================
# Target rules for targets named TestShaderDefault2DWebGPU

# Build rule for target.
TestShaderDefault2DWebGPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestShaderDefault2DWebGPU
.PHONY : TestShaderDefault2DWebGPU

# fast build rule for target.
TestShaderDefault2DWebGPU/fast:
	$(MAKE) -f TestShaderDefault2D/CMakeFiles/TestShaderDefault2DWebGPU.dir/build.make TestShaderDefault2D/CMakeFiles/TestShaderDefault2DWebGPU.dir/build
.PHONY : TestShaderDefault2DWebGPU/fast

#=============================================================================
# Target rules for targets named TestShaderDefault3DWebGPU

# Build rule for target.
TestShaderDefault3DWebGPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestShaderDefault3DWebGPU
.PHONY : TestShaderDefault3DWebGPU

# fast build rule for target.
TestShaderDefault3DWebGPU/fast:
	$(MAKE) -f TestShaderDefault3D/CMakeFiles/TestShaderDefault3DWebGPU.dir/build.make TestShaderDefault3D/CMakeFiles/TestShaderDefault3DWebGPU.dir/build
.PHONY : TestShaderDefault3DWebGPU/fast

#=============================================================================
# Target rules for targets named TestShaderBlockGameWebGPU

# Build rule for target.
TestShaderBlockGameWebGPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestShaderBlockGameWebGPU
.PHONY : TestShaderBlockGameWebGPU

# fast build rule for target.
TestShaderBlockGameWebGPU/fast:
	$(MAKE) -f TestShaderBlockGame/CMakeFiles/TestShaderBlockGameWebGPU.dir/build.make TestShaderBlockGame/CMakeFiles/TestShaderBlockGameWebGPU.dir/build
.PHONY : TestShaderBlockGameWebGPU/fast

#=============================================================================
# Target rules for targets named TestShaderExtractBrightWebGPU

# Build rule for target.
TestShaderExtractBrightWebGPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestShaderExtractBrightWebGPU
.PHONY : TestShaderExtractBrightWebGPU

# fast build rule for target.
TestShaderExtractBrightWebGPU/fast:
	$(MAKE) -f TestShaderExtractBright/CMakeFiles/TestShaderExtractBrightWebGPU.dir/build.make TestShaderExtractBright/CMakeFiles/TestShaderExtractBrightWebGPU.dir/build
.PHONY : TestShaderExtractBrightWebGPU/fast

#=============================================================================
# Target rules for targets named TestShaderForwardFogWebGPU

# Build rule for target.
TestShaderForwardFogWebGPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestShaderForwardFogWebGPU
.PHONY : TestShaderForwardFogWebGPU

# fast build rule for target.
TestShaderForwardFogWebGPU/fast:
	$(MAKE) -f TestShaderForwardFog/CMakeFiles/TestShaderForwardFogWebGPU.dir/build.make TestShaderForwardFog/CMakeFiles/TestShaderForwardFogWebGPU.dir/build
.PHONY : TestShaderForwardFogWebGPU/fast

#=============================================================================
# Target rules for targets named TestShaderForwardTriplanarWebGPU

# Build rule for target.
TestShaderForwardTriplanarWebGPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestShaderForwardTriplanarWebGPU
.PHONY : TestShaderForwardTriplanarWebGPU

# fast build rule for target.
TestShaderForwardTriplanarWebGPU/fast:
	$(MAKE) -f TestShaderForwardTriplanar/CMakeFiles/TestShaderForwardTriplanarWebGPU.dir/build.make TestShaderForwardTriplanar/CMakeFiles/TestShaderForwardTriplanarWebGPU.dir/build
.PHONY : TestShaderForwardTriplanarWebGPU/fast

#=============================================================================
# Target rules for targets named TestShaderGameOfLifeWebGPU

# Build rule for target.
TestShaderGameOfLifeWebGPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestShaderGameOfLifeWebGPU
.PHONY : TestShaderGameOfLifeWebGPU

# fast build rule for target.
TestShaderGameOfLifeWebGPU/fast:
	$(MAKE) -f TestShaderGameOfLife/CMakeFiles/TestShaderGameOfLifeWebGPU.dir/build.make TestShaderGameOfLife/CMakeFiles/TestShaderGameOfLifeWebGPU.dir/build
.PHONY : TestShaderGameOfLifeWebGPU/fast

#=============================================================================
# Target rules for targets named TestShaderGrayScaleWebGPU

# Build rule for target.
TestShaderGrayScaleWebGPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestShaderGrayScaleWebGPU
.PHONY : TestShaderGrayScaleWebGPU

# fast build rule for target.
TestShaderGrayScaleWebGPU/fast:
	$(MAKE) -f TestShaderGrayScale/CMakeFiles/TestShaderGrayScaleWebGPU.dir/build.make TestShaderGrayScale/CMakeFiles/TestShaderGrayScaleWebGPU.dir/build
.PHONY : TestShaderGrayScaleWebGPU/fast

#=============================================================================
# Target rules for targets named TestShaderMultiTextureBlendWebGPU

# Build rule for target.
TestShaderMultiTextureBlendWebGPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestShaderMultiTextureBlendWebGPU
.PHONY : TestShaderMultiTextureBlendWebGPU

# fast build rule for target.
TestShaderMultiTextureBlendWebGPU/fast:
	$(MAKE) -f TestShaderMultiTextureBlend/CMakeFiles/TestShaderMultiTextureBlendWebGPU.dir/build.make TestShaderMultiTextureBlend/CMakeFiles/TestShaderMultiTextureBlendWebGPU.dir/build
.PHONY : TestShaderMultiTextureBlendWebGPU/fast

#=============================================================================
# Target rules for targets named TestShaderMultiShaderMaskWebGPU

# Build rule for target.
TestShaderMultiShaderMaskWebGPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestShaderMultiShaderMaskWebGPU
.PHONY : TestShaderMultiShaderMaskWebGPU

# fast build rule for target.
TestShaderMultiShaderMaskWebGPU/fast:
	$(MAKE) -f TestShaderMultiShaderMask/CMakeFiles/TestShaderMultiShaderMaskWebGPU.dir/build.make TestShaderMultiShaderMask/CMakeFiles/TestShaderMultiShaderMaskWebGPU.dir/build
.PHONY : TestShaderMultiShaderMaskWebGPU/fast

#=============================================================================
# Target rules for targets named TestShaderPoissonDiskWebGPU

# Build rule for target.
TestShaderPoissonDiskWebGPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestShaderPoissonDiskWebGPU
.PHONY : TestShaderPoissonDiskWebGPU

# fast build rule for target.
TestShaderPoissonDiskWebGPU/fast:
	$(MAKE) -f TestShaderPoissonDisk/CMakeFiles/TestShaderPoissonDiskWebGPU.dir/build.make TestShaderPoissonDisk/CMakeFiles/TestShaderPoissonDiskWebGPU.dir/build
.PHONY : TestShaderPoissonDiskWebGPU/fast

#=============================================================================
# Target rules for targets named TestShaderPosterizeWebGPU

# Build rule for target.
TestShaderPosterizeWebGPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestShaderPosterizeWebGPU
.PHONY : TestShaderPosterizeWebGPU

# fast build rule for target.
TestShaderPosterizeWebGPU/fast:
	$(MAKE) -f TestShaderPosterize/CMakeFiles/TestShaderPosterizeWebGPU.dir/build.make TestShaderPosterize/CMakeFiles/TestShaderPosterizeWebGPU.dir/build
.PHONY : TestShaderPosterizeWebGPU/fast

#=============================================================================
# Target rules for targets named TestShaderRGBShiftWebGPU

# Build rule for target.
TestShaderRGBShiftWebGPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestShaderRGBShiftWebGPU
.PHONY : TestShaderRGBShiftWebGPU

# fast build rule for target.
TestShaderRGBShiftWebGPU/fast:
	$(MAKE) -f TestShaderRGBShift/CMakeFiles/TestShaderRGBShiftWebGPU.dir/build.make TestShaderRGBShift/CMakeFiles/TestShaderRGBShiftWebGPU.dir/build
.PHONY : TestShaderRGBShiftWebGPU/fast

#=============================================================================
# Target rules for targets named TestShaderRGBToBGRWebGPU

# Build rule for target.
TestShaderRGBToBGRWebGPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestShaderRGBToBGRWebGPU
.PHONY : TestShaderRGBToBGRWebGPU

# fast build rule for target.
TestShaderRGBToBGRWebGPU/fast:
	$(MAKE) -f TestShaderRGBToBGR/CMakeFiles/TestShaderRGBToBGRWebGPU.dir/build.make TestShaderRGBToBGR/CMakeFiles/TestShaderRGBToBGRWebGPU.dir/build
.PHONY : TestShaderRGBToBGRWebGPU/fast

#=============================================================================
# Target rules for targets named TestShaderSwirlWebGPU

# Build rule for target.
TestShaderSwirlWebGPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestShaderSwirlWebGPU
.PHONY : TestShaderSwirlWebGPU

# fast build rule for target.
TestShaderSwirlWebGPU/fast:
	$(MAKE) -f TestShaderSwirl/CMakeFiles/TestShaderSwirlWebGPU.dir/build.make TestShaderSwirl/CMakeFiles/TestShaderSwirlWebGPU.dir/build
.PHONY : TestShaderSwirlWebGPU/fast

#=============================================================================
# Target rules for targets named TestShaderTerrainNormalWebGPU

# Build rule for target.
TestShaderTerrainNormalWebGPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestShaderTerrainNormalWebGPU
.PHONY : TestShaderTerrainNormalWebGPU

# fast build rule for target.
TestShaderTerrainNormalWebGPU/fast:
	$(MAKE) -f TestShaderTerrainNormal/CMakeFiles/TestShaderTerrainNormalWebGPU.dir/build.make TestShaderTerrainNormal/CMakeFiles/TestShaderTerrainNormalWebGPU.dir/build
.PHONY : TestShaderTerrainNormalWebGPU/fast

#=============================================================================
# Target rules for targets named Test3DCase1WebGPU

# Build rule for target.
Test3DCase1WebGPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Test3DCase1WebGPU
.PHONY : Test3DCase1WebGPU

# fast build rule for target.
Test3DCase1WebGPU/fast:
	$(MAKE) -f Test3DCase1/CMakeFiles/Test3DCase1WebGPU.dir/build.make Test3DCase1/CMakeFiles/Test3DCase1WebGPU.dir/build
.PHONY : Test3DCase1WebGPU/fast

#=============================================================================
# Target rules for targets named Test3DCase2WebGPU

# Build rule for target.
Test3DCase2WebGPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Test3DCase2WebGPU
.PHONY : Test3DCase2WebGPU

# fast build rule for target.
Test3DCase2WebGPU/fast:
	$(MAKE) -f Test3DCase2/CMakeFiles/Test3DCase2WebGPU.dir/build.make Test3DCase2/CMakeFiles/Test3DCase2WebGPU.dir/build
.PHONY : Test3DCase2WebGPU/fast

#=============================================================================
# Target rules for targets named Test3DCase3WebGPU

# Build rule for target.
Test3DCase3WebGPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Test3DCase3WebGPU
.PHONY : Test3DCase3WebGPU

# fast build rule for target.
Test3DCase3WebGPU/fast:
	$(MAKE) -f Test3DCase3/CMakeFiles/Test3DCase3WebGPU.dir/build.make Test3DCase3/CMakeFiles/Test3DCase3WebGPU.dir/build
.PHONY : Test3DCase3WebGPU/fast

#=============================================================================
# Target rules for targets named Test3DCase4WebGPU

# Build rule for target.
Test3DCase4WebGPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Test3DCase4WebGPU
.PHONY : Test3DCase4WebGPU

# fast build rule for target.
Test3DCase4WebGPU/fast:
	$(MAKE) -f Test3DCase4/CMakeFiles/Test3DCase4WebGPU.dir/build.make Test3DCase4/CMakeFiles/Test3DCase4WebGPU.dir/build
.PHONY : Test3DCase4WebGPU/fast

#=============================================================================
# Target rules for targets named Test3DShadingWebGPU

# Build rule for target.
Test3DShadingWebGPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Test3DShadingWebGPU
.PHONY : Test3DShadingWebGPU

# fast build rule for target.
Test3DShadingWebGPU/fast:
	$(MAKE) -f Test3DShading/CMakeFiles/Test3DShadingWebGPU.dir/build.make Test3DShading/CMakeFiles/Test3DShadingWebGPU.dir/build
.PHONY : Test3DShadingWebGPU/fast

#=============================================================================
# Target rules for targets named Test3DSkyWebGPU

# Build rule for target.
Test3DSkyWebGPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Test3DSkyWebGPU
.PHONY : Test3DSkyWebGPU

# fast build rule for target.
Test3DSkyWebGPU/fast:
	$(MAKE) -f Test3DSky/CMakeFiles/Test3DSkyWebGPU.dir/build.make Test3DSky/CMakeFiles/Test3DSkyWebGPU.dir/build
.PHONY : Test3DSkyWebGPU/fast

#=============================================================================
# Target rules for targets named TestSRGBCase1WebGPU

# Build rule for target.
TestSRGBCase1WebGPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestSRGBCase1WebGPU
.PHONY : TestSRGBCase1WebGPU

# fast build rule for target.
TestSRGBCase1WebGPU/fast:
	$(MAKE) -f TestSRGBCase1/CMakeFiles/TestSRGBCase1WebGPU.dir/build.make TestSRGBCase1/CMakeFiles/TestSRGBCase1WebGPU.dir/build
.PHONY : TestSRGBCase1WebGPU/fast

#=============================================================================
# Target rules for targets named TestSRGBCase2WebGPU

# Build rule for target.
TestSRGBCase2WebGPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestSRGBCase2WebGPU
.PHONY : TestSRGBCase2WebGPU

# fast build rule for target.
TestSRGBCase2WebGPU/fast:
	$(MAKE) -f TestSRGBCase2/CMakeFiles/TestSRGBCase2WebGPU.dir/build.make TestSRGBCase2/CMakeFiles/TestSRGBCase2WebGPU.dir/build
.PHONY : TestSRGBCase2WebGPU/fast

#=============================================================================
# Target rules for targets named TestSRGBCase3WebGPU

# Build rule for target.
TestSRGBCase3WebGPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestSRGBCase3WebGPU
.PHONY : TestSRGBCase3WebGPU

# fast build rule for target.
TestSRGBCase3WebGPU/fast:
	$(MAKE) -f TestSRGBCase3/CMakeFiles/TestSRGBCase3WebGPU.dir/build.make TestSRGBCase3/CMakeFiles/TestSRGBCase3WebGPU.dir/build
.PHONY : TestSRGBCase3WebGPU/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Siv3DAppData"
	@echo "... MainWebGPU"
	@echo "... AsyncFileDownloadWebGPU"
	@echo "... DragDropWebGPU"
	@echo "... MicrophoneWebGPU"
	@echo "... MaterialIconWebGPU"
	@echo "... QRReaderWebGPU"
	@echo "... TerrainWebGPU"
	@echo "... VideoReaderWebGPU"
	@echo "... WebCamWebGPU"
	@echo "... AdditionalEmojiWebGPU"
	@echo "... EmpoweredAudioWebGPU"
	@echo "... KDTreeWebGPU"
	@echo "... GeoJsonWebGPU"
	@echo "... GrabCutWebGPU"
	@echo "... Spline2DWebGPU"
	@echo "... P2WheelJointWebGPU"
	@echo "... PackRectanglesWebGPU"
	@echo "... PolygonOutlineWebGPU"
	@echo "... PerlinNoiseWebGPU"
	@echo "... QRCodeWebGPU"
	@echo "... RayIntersectionWebGPU"
	@echo "... NavMeshWebGPU"
	@echo "... SoftShapeWebGPU"
	@echo "... ViewFrustumWebGPU"
	@echo "... TCPonWebSocketWebGPU"
	@echo "... TestShaderDefault2DWebGPU"
	@echo "... TestShaderDefault3DWebGPU"
	@echo "... TestShaderBlockGameWebGPU"
	@echo "... TestShaderExtractBrightWebGPU"
	@echo "... TestShaderForwardFogWebGPU"
	@echo "... TestShaderForwardTriplanarWebGPU"
	@echo "... TestShaderGameOfLifeWebGPU"
	@echo "... TestShaderGrayScaleWebGPU"
	@echo "... TestShaderMultiTextureBlendWebGPU"
	@echo "... TestShaderMultiShaderMaskWebGPU"
	@echo "... TestShaderPoissonDiskWebGPU"
	@echo "... TestShaderPosterizeWebGPU"
	@echo "... TestShaderRGBShiftWebGPU"
	@echo "... TestShaderRGBToBGRWebGPU"
	@echo "... TestShaderSwirlWebGPU"
	@echo "... TestShaderTerrainNormalWebGPU"
	@echo "... Test3DCase1WebGPU"
	@echo "... Test3DCase2WebGPU"
	@echo "... Test3DCase3WebGPU"
	@echo "... Test3DCase4WebGPU"
	@echo "... Test3DShadingWebGPU"
	@echo "... Test3DSkyWebGPU"
	@echo "... TestSRGBCase1WebGPU"
	@echo "... TestSRGBCase2WebGPU"
	@echo "... TestSRGBCase3WebGPU"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

